name: Docker Fast Deploy

on:
  push:
    branches: [ "master" ]

env:
  DEPLOY_DIR: ~/spahtmx

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}:latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy source to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          source: "docker-compose.yml,nobel-prize.json"
          target: ${{ env.DEPLOY_DIR }}
          overwrite: true

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          envs: GITHUB_TOKEN
          script: |
            cd ${{ env.DEPLOY_DIR }}
            export IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
            echo $GITHUB_TOKEN | podman login ghcr.io -u ${{ github.actor }} --password-stdin
            podman pull $IMAGE_NAME
            systemctl --user restart spahtmx
